### ISSUE TITLE
super obvious link to backpack

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges.org#16]
provide a very visible link to the backpack on openbadges.org

**Comment by threeqube** [comment]
+1 on this from one of the folks we work with. Comments from him below:

From: "Richard Culatta" Richard.Culatta@ed.gov
To: sunny@mozillafoundation.org
Cc: "Jason Hoekstra" Jason.Hoekstra@ed.gov
Sent: Tuesday, April 17, 2012 9:33:50 AM
Subject: Link to Badge Backpack

Hi Sunny - I'm doing a series of keynotes about the transition to print to digital and hope to give some good examples of how badges could fit in.  One question, though...  Is there any reason why the link to the Badge Backback is so hard to find?  Is there any way that could be made more prominent on the open badges site?  It would sure make it easier for me to explain to people if there was a way for them to actually see the backback.
Thanks!
-R

## 

Richard Culatta
Deputy Director, Office of Educational Technology
US Department of Education
