### ISSUE TITLE
mobile viewing

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges.org#17]
From mozilla/openbadges#125:

Try out the web site http://openbadges.org/ on a phone. (I used an iPhone). The result is not nice. (Screenshot here: http://lockerz.com/s/200910234 )

Fast and easy fix would be to remove the viewport meta-tag. 
Fix in the future would be to build mobile first and/or use media queries to correct styling when the browser window is tiny.

**Comment by stenington** [comment]
I'm leaving this issue open as an enhancement to one day build a mobile version of the site.

**Comment by brianloveswords** [comment]
http://mediaqueri.es/

Some inspiration.
