### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by threeqube** [mozilla/openbadges.org#18]
Accessibility considerations

**Comment by davidascher** [comment]
How important is this, and for which market & timeline?  

In particular -- In my experience Mozilla tends to shoot for accessibility of a variety of forms (including ARIA support, etc.), but not actual 508 compliance in any "serious" way (which I believe requires third party audits, etc.)

Formal 508 compliance tends to become a strict requirement for US government contracts.

**Comment by threeqube** [comment]
I don't think formal 508 compliance but some level of accessibility considerations. I'll change the issue to clarify.
