### ISSUE TITLE
Fix validation errors

### ISSUE THREAD

**Issue by icaaq** [mozilla/openbadges.org#19]
Add alt attributes on all of the images and close the b-element on line 56 column 25

http://validator.w3.org/check?verbose=1&uri=http%3A%2F%2Fopenbadges.org%2Fen-US%2F

**Comment by stenington** [comment]
Fixed the b-element part of this here b47c6823f7c8f4af5f143c77bfa9b9accd8c4504

**Comment by stenington** [comment]
[Woot!](http://validator.w3.org/check?uri=http%3A%2F%2Fopenbadges.toolness.org%2Fen-US%2F;verbose=1)
