### ISSUE TITLE
Hash email address for test badge.

### ISSUE THREAD

**Issue by brianloveswords** [mozilla/openbadges.org#42]
We should be hashing the email address for the test badges to comply with the latest version of the badge specification.

**Comment by brianloveswords** [comment]
https://github.com/mozilla/openbadges.org/blob/development/static/scripts/main.js#L50 is the spot where we should be hashing it.

Problem is that browsers don't provide hash methods natively.

We could solve that by including something like this: http://www.bichlmeier.info/sha256.js.

**Comment by stenington** [comment]
Okeydoke. f8104a274de385c1bb6805770e16aed240b9d43c

**Comment by brianloveswords** [comment]
Awesome. Awesome to the max.
