### ISSUE TITLE
"Legal Notices" on landing page footer should say "Terms of Use" and direct to Open Badges TOU not Mozilla legal notices

### ISSUE THREAD

**Issue by threeqube** [mozilla/openbadges.org#53]
Jishnu Menon, our Moco legal counsel, suggested that instead of "Legal Notices" on the footer of our landing page http://openbadges.org/en-US/ we change that to "Terms of Use" and point to our Open Badges TOU http://beta.openbadges.org/tou.html instead

**Comment by stenington** [comment]
I think this is done.
