### ISSUE TITLE
508 Accessibility Documentation for OpenBadges.org

### ISSUE THREAD

**Issue by emgollie** [mozilla/openbadges.org#63]
@stenington will be reviewing OpenBadges.org for VPAT documentation that will be hosted on the site. Individual issues about what we are able to support may follow.

https://openbadges.etherpad.mozilla.org/508-accessibility

**Comment by stenington** [comment]
@emgollie I've made notes in the etherpad. I think there's a little bit of work to do; we can discuss and write up specific github issues as necessary.

**Comment by stenington** [comment]
Also, this was the work by crasx that we can reference and try to make us of, if we want to: https://github.com/mozilla/openbadges.org/pull/56

**Comment by emgollie** [comment]
Discussed with @stenington. Appreciate the pad updates. Next steps are: 

@stenington to complete first pass
@threeqube and I to review, prep for site
Linked version to be made available on OpenBadges.org footer

**Comment by stenington** [comment]
@emgollie @threeqube I think we might have to do more than just the 1194.22 section. I can't find an example of a site that just does that one section. For example, Gmail does .21, .22, .31 and .41, which seems to be the norm:

<img src="http://f.cl.ly/items/1e1f0o33051G2t222A1i/13.png">

I'll create a VPAT listing those sections as "Not Applicable" for now, but I have a growing suspicion that's wrong.

**Comment by stenington** [comment]
Digging in to this a little more, the pattern I'm seeing is that a company will host VPATs for each product, but not also a VPAT for the site itself. So for example, I can't find a VPAT for google.com, but I found [this site](http://www.google.com/accessibility/policy/) listing VPATs for their various webapp offerings.

So maybe we should be hosting the Backpack VPAT at openbadges.org, but the .org site doesn't need its own?

**Comment by emgollie** [comment]
Thanks @stenington. We were initially informed by an accessibility pro member of the community (whose original note I'll dig up) that .22 is the only paperwork we need to complete given the nature of OpenBadges.org. If you look at the Moz VPAT (http://www.mozilla.org/en-US/firefox/vpat-3.html), I don't think we qualify for these:

.21 Software Applications and Operating Systems
.23 Telecommunications Products 
.24 Video and Multi-media Products
.25 Self-Contained, Closed Products
.26 Desktop and Portable Computers

.31 and .41 may be more important re: providing support detail. We may want to list our reporting in the same format (with all portions listed but "Not applicable" being listed for several sections). Thoughts?

**Comment by stenington** [comment]
So that's the thing: the Moz VPAT is for the Firefox browser. I don't think there's a VPAT for the mozilla.org website or anything. I can't find any examples of VPATs for websites, only web apps.

**Comment by threeqube** [comment]
You make a good point @stenington regarding not needing one for openbages.org. Ok, well then let's just do it for the backpack for now until we find anything contradictory. 

Regarding VPAT provisions in other areas like .21, .23, .23, .25, .26, none of these really seem to apply to us. Maybe .21 software application? Should we just additionally fill out .21? Don't think we need to fill things out that just are not applicable.

**Comment by emgollie** [comment]
It sounds like we can forgo .23, .24, .25, and .26. @stenington recommends completing .21, .31, and .41.
