### ISSUE TITLE
Badges 101 Criteria page badges-101.openbadges.org needs to be created or redirect

### ISSUE THREAD

**Issue by davelester** [mozilla/openbadges.org#68]
The url badges-101.openbadges.org in the Badges 101 assertion file returns a 404 error, which particularly problematic for badge display that may link to this url. A few options to fix this problem:
1. Create a badge criteria page at badges-101.openbadges.org
2. Don't create a new page, and instead redirect badges-101.openbadges.org to openbadges.org

The first option seems ideal to me, because it models the basics of how we'd like criteria pages to work for n00bs.@brianloveswords suggested option two in IRC.

**Comment by threeqube** [comment]
I sort of prefer the former as well. Our current solution of redirecting is not reflection of good practices. @emgollie and I can put together the content for the page. As an fyi, we're putting together requirements of a redesign of the current website. We want to really show clearly that first and foremost Open Badges is a badge standard and that is so buried at the moment. Having a criteria page should be part of the redesign effort.

**Comment by emgollie** [comment]
+1 what @threeqube shared. Adding badge criteria page to our deliverables.

**Comment by brianloveswords** [comment]
Sounds good. I suggested option 2 because it was easier to deliver. Either way, we'll have to request some action from MoCo Ops.

**Comment by davelester** [comment]
Sounds good. It may make sense to issue these badges using https://badges.webmaker.org to avoid random subdomains hosting assertion files.

**Comment by stenington** [comment]
The Badges 101 badge isn't a Webmaker badge though. It's not earnable through Thimble, so it shouldn't get listed on https://badges.webmaker.org. We could consider secretly hosting it there once we have better badge listing options in place on openbadger.

**Comment by threeqube** [comment]
+1 @stenington Badges 101 badge isn't a webmaker badge.
