### ISSUE TITLE
Move this thing to Wordpress

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadges.org#69]
Leave all content as is, but serve it from a Wordpress install. Use WPBadger for the badges 101 quiz. Otherwise, a straight port to Wordpress.

**Comment by jdotpz** [comment]
openbadgesorg.mofostaging.net is up and ready, but this will not be 'prod'.

**Comment by jdotpz** [comment]
http://54.235.153.99/ is up, running bitnami wordpress 3.5.0.
Newrelic monitoring dashboard: https://rpm.newrelic.com/accounts/255689/custom_dashboards/1695/pages/2312

A few things we want to do:

#MUST BE DONE PRELAUNCH
- [x] Setup monitoring and alerting on RDS
- [x] Setup monitoring and alerting on wp nodes
- [ ]  Setup metrics in geckoboard
- [x] Setup ELB
- [x] fix /wordpress/ paths (what a pita!)
- [ ] set up redirects for current URLs
- [x] TODAY - Get openbadges.org cert
- [x] TODAY - Get openbadges.org DNS ttl's pushed down(Gozer)

#NICE TO HAVE
- [x] w3_total_cache installed/used http://cykod.com/blog/post/2010-09-blogging-in-the-cloud-scaling-wordpress3
- [ ] S3 bucket setup and used
- [ ] - Cloudwatch stats --> geckoboard/opsview
- [ ]  Setup autoscale group with images
- [ ]  logs going to logging aggregator

**Comment by rossbruniges** [comment]
Quick note - the latest stable wordpress is now 3.5.1

**Comment by jdotpz** [comment]
DB monitoring is up: http://opsview.mofoprod.net:3000/status/service?host=OpenbadgesOrg-Production-DB

**Comment by jdotpz** [comment]
Got the cert from Gozer, installed on a new ELB, and installed SSL plugin for wordpress.

**Comment by jdotpz** [comment]
cc @cmcavoy @andrewhayward 
I've fixed the paths, so wordpress is no longer in any url.  Ive also setup a small memcache node and installed the w3_total_cache plugin, and pointed page, object, and database cache at the memcache cname openbadgesorg-cache-c.mofoprod.net:11211

**Comment by jdotpz** [comment]
So after tuning this a bit and getting caching up, etc, load tests showed a much happier app.

Earlier( https://rpm.newrelic.com/accounts/255689/notes/1658 )
-~2 requests per second before app was slow

Now( https://rpm.newrelic.com/accounts/255689/notes/1660 )
~80 requests per second.

:)
cc @rossbruniges @andrewhayward @cmcavoy

**Comment by rossbruniges** [comment]
That sounds like a win to me JP!!

**Comment by jdotpz** [comment]
Well, using this type of setup, I can achieve incredible throughput.
http://www.ewanleith.com/blog/900/10-million-hits-a-day-with-wordpress-using-a-15-server
I have a micro running that can handle just a ton of requests, i got it up to ~15k per second.

**Comment by jdotpz** [comment]
I'm willing to give it a shot with the openbadges.org site, if we want.

**Comment by brianloveswords** [comment]
It's moved, right?!

**Comment by jdotpz** [comment]
Yup, it is.  
![BTMueqb](https://f.cloud.github.com/assets/1373628/254767/475ef666-8bfb-11e2-874b-6cc12bccd96a.gif)
