### ISSUE TITLE
Drop in new logo into site

### ISSUE THREAD

**Issue by threeqube** [mozilla/openbadges.org#76]

**Comment by threeqube** [comment]
@emgollie Can we get finalized assets that we can use to drop into our openbadges.org site in time for DML?

**Comment by emgollie** [comment]
Yes. Finalizing logo colors and wordmark font and then will get layered PSD files over (unless another format is needed--do we know who will be making these frontend edits?). // cc @stenington

**Comment by threeqube** [comment]
@cmcavoy will help with assignments.
