### ISSUE TITLE
Get rid of Gladys talk bubble or think of different content for her

### ISSUE THREAD

**Issue by threeqube** [mozilla/openbadges.org#79]
@emgollie thoughts on Gladys thought bubble? cc/ @iamjessklein

**Comment by emgollie** [comment]
For DML let's have her say "Check out the redesigned Backpack!" ("the" vs. "your" as many people who visit this page won't have their own Backpack yet)

Then for 1.5 we can add the new openbadges.org look and feel.

**Comment by threeqube** [comment]
I like the idea of pointing people to the new backpack.
