### ISSUE TITLE
Add Open Badges insignia to the Issuer page http://openbadges.org/issuer/

### ISSUE THREAD

**Issue by threeqube** [mozilla/openbadges.org#80]
On the issuer page, add open badge insignias that indicate that an organization is issuing OBI aligned badges. 

@emgollie to draft instructions.

**Comment by emgollie** [comment]
This is detailed at https://app.asana.com/0/2038783115031/2790541669834 for the comms team.

We want to make these four issuer insignia options available by DML. These will be downloadable image files (eventually we'd like to make them embeddable, but that isn't in scope for DML).

We will ask that issuers post them on their websites and link to openbadges.org starting Thursday's announcement. I can write the instructions for the issuer page on openbadges.org. @cmcavoy, would you mind letting me know who else you'd like to have work on this? 

![OpenBadges_Insignia_WeIssue](https://f.cloud.github.com/assets/1174853/235373/79a0b4e2-87a1-11e2-9b05-071b3cdbe7f0.png)
![OpenBadges_Insignia_WeIssue_Banner](https://f.cloud.github.com/assets/1174853/235375/910f90bc-87a1-11e2-9151-1551bcc0df26.png)
![OpenBadges_Insignia_EarnOur](https://f.cloud.github.com/assets/1174853/235376/9a96d028-87a1-11e2-9f91-33b683ddf54e.png)
![OpenBadges_Insignia_EarnOur_Banner](https://f.cloud.github.com/assets/1174853/235377/9edba032-87a1-11e2-8e67-587c271a564a.png)

**Comment by cmcavoy** [comment]
@emgollie I think we (you and I) can handle getting the page online ourselves with the fancy new Wordpress install. :+1:

**Comment by emgollie** [comment]
Sounds great. Team Megabus has got this. I will draft the copy along with the other issuer page additions.

**Comment by emgollie** [comment]
Draft insignia uploading copy for openbadges.org/issuers can be found at https://etherpad.mozilla.org/OpenBadges-website, line 154:

Website Insignias for Current Issuers
You've asked and we've answered! Insignias are now available for issuers' websites. To feature one of these:
- Download one of these images;
- Decide where you want to place it on your website and add it to your site's front end;
- Link the image to http://openbadges.org so that interested people can learn about the ecosystem you're a part of;
- Ensure that it's possible for people to easily find information about badges you issue on your site;
- Reach out to Mozilla (email hyperlink) with questions. 

What instructions are missing? cc @cmcavoy @threeqube

**Comment by emgollie** [comment]
Spacing needs work and links need to be added during editing, but an updated version is here: http://openbadgesorg.mofostaging.net/issuer/

**Comment by threeqube** [comment]
I think that covers it. Should we say we'll make it embeddable soon?

**Comment by emgollie** [comment]
I like that idea @threeqube. @cmcavoy, do you have a sense for when time-wise we might be able to make the insignias embeddable? 

Would we ever consider integrating them with the OBI and defining fields for what it means to be an issuer (from a technical perspective only?)

**Comment by threeqube** [comment]
@emgollie let's keep it vague. We'll make it embeddable soon! Something like that.

**Comment by emgollie** [comment]
Agree. Should have clarified that those are questions that I have for internal timing for openbadges.org.

**Comment by cmcavoy** [comment]
>  @cmcavoy, do you have a sense for when time-wise we might be able to make the insignias embeddable? 

Soon after 1.0? Just need to figure out what we want from the embed-ability...etc.

**Comment by emgollie** [comment]
@cmcavoy @threeqube Would you mind reviewing this page that will host the insignias?

http://openbadgesorg.mofostaging.net/insignia/

**Comment by threeqube** [comment]
:+1:
