### ISSUE TITLE
openbadges.org homepage: Replace Earner | Issuer | Displayer icons with new cube imagery

### ISSUE THREAD

**Issue by emgollie** [mozilla/openbadges.org#81]
@iamjessklein, can we replace the icons that are currently assigned to Earner | Issuer | Displayer on the homepage with the new cubes that Ocupop created (available here: https://www.dropbox.com/sh/4cupc1w1xairnif/fa3oAdVz0F)?
![Screen Shot 2013-03-08 at 9 18 14 AM](https://f.cloud.github.com/assets/1174853/237780/5a84097c-8820-11e2-99e7-3596eb200ad0.png)

cc @threeqube

**Comment by threeqube** [comment]
Reassigning to @cappleton
