### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadges.org#9]
We received outside offers of localization, need the framework to support it.

**Comment by threeqube** [comment]
More info from community member from France:

From: "Julia Buchner" julia@buchner.fr
To: "Sunny Lee" sunny@mozillafoundation.org
Sent: Wednesday, April 11, 2012 1:04:31 PM
Subject: Localization for Open Badges

Hi,

As we talked about yesterday on IRC, I have now more information from the localization manager:

```
1. first of all, we have to choose a format for localization : https://developer.mozilla.org/en/Web_Localizability/localization_formats. The best option for an existing website is gettext: https://developer.mozilla.org/en/gettext.
2. if we use gettext, we have to prepare the website for localization, by wrapping all strings with gettext methods.
3. we have to open a localization bug on Bugzilla and wait for a response.
```

I spoke with the manager of the localization team and he gave me some advice:
- it's a good idea to test a localization with one or few languages, and after ask for more languages. We can test with French (which I can review) or with Spanish (where the community has more volunteer than work). I'll talk with one of Spanish team, so we can work with them.
- we have to freeze website's string : if we change one of them without changing the localization and getting a new .po file, the localization will be break.

**Comment by threeqube** [comment]
Can we revisit this?

**Comment by cmcavoy** [comment]
Think this is the wrong place to put discuss this...are we talking about localizing the backpack? Or the specification?
