### ISSUE TITLE
Tweak language on About page

### ISSUE THREAD

**Issue by erinknight** [mozilla/openbadges.org#90]
Please change the last paragraph to read: 

Open Badges started as a collaborative project between MacArthur Foundation, HASTAC and Mozilla and has continued to grow through an open, collaborative approach. It is designed, built and backed by a broad community of contributors, such as NASA, the Smithsonian, Intel, the Girl Scouts, and more. The open source model means that improvements made by one partner can benefit everyone, from bug fixes to new features. Open Badges logos and visual assets are here.

**Comment by threeqube** [comment]
Updated: http://openbadges.org/about/
